[package]
name = "loom-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
reqwest.workspace = true
serde_json.workspace = true
uuid.workspace = true
loom-types = { path = "../loom-types" }
